local Registry = require("lib.registry")

describe("Registry", function()
  it("register adds a node retrievable via get()", function()
    local r = Registry.new()
    r:register({ id = 7, label = "farm-east" }, 1000)
    local node = r:get(7)
    assert.truthy(node)
    assert.equals(node.id, 7)
    assert.equals(node.label, "farm-east")
    assert.equals(node.status, "Ready")
    assert.equals(node.last_seen, 1000)
  end)

  it("heartbeat updates last_seen", function()
    local r = Registry.new()
    r:register({ id = 7 }, 1000)
    r:heartbeat(7, 2000)
    assert.equals(r:get(7).last_seen, 2000)
  end)

  it("heartbeat on unknown id is a no-op", function()
    local r = Registry.new()
    r:heartbeat(99, 1000)
    assert.is_nil(r:get(99))
  end)

  it("tick: node within timeout stays Ready", function()
    local r = Registry.new({ timeout_seconds = 45 })
    r:register({ id = 7 }, 1000)
    r:tick(1040)
    assert.equals(r:get(7).status, "Ready")
  end)

  it("tick: node past timeout becomes NotReady", function()
    local r = Registry.new({ timeout_seconds = 45 })
    r:register({ id = 7 }, 1000)
    r:tick(1050)
    assert.equals(r:get(7).status, "NotReady")
  end)

  it("tick: node past eviction_seconds is removed", function()
    local r = Registry.new({ timeout_seconds = 45, eviction_seconds = 300 })
    r:register({ id = 7 }, 1000)
    r:tick(1301)
    assert.is_nil(r:get(7))
  end)

  it("register on existing id is an upsert — resets to Ready", function()
    local r = Registry.new({ timeout_seconds = 45 })
    r:register({ id = 7 }, 1000)
    r:tick(1050)
    assert.equals(r:get(7).status, "NotReady")
    r:register({ id = 7 }, 1060)
    assert.equals(r:get(7).status, "Ready")
    assert.equals(r:get(7).last_seen, 1060)
  end)

  it("upsert preserves existing label when not provided", function()
    local r = Registry.new()
    r:register({ id = 7, label = "farm-east" }, 1000)
    r:register({ id = 7 }, 2000)
    assert.equals(r:get(7).label, "farm-east")
  end)

  it("nodes() returns all records sorted by id", function()
    local r = Registry.new()
    r:register({ id = 3 }, 1000)
    r:register({ id = 1 }, 1000)
    r:register({ id = 2 }, 1000)
    local all = r:nodes()
    assert.equals(#all, 3)
    assert.equals(all[1].id, 1)
    assert.equals(all[2].id, 2)
    assert.equals(all[3].id, 3)
  end)

  it("ready_nodes() excludes NotReady nodes", function()
    local r = Registry.new({ timeout_seconds = 45 })
    r:register({ id = 1 }, 1000)
    r:register({ id = 2 }, 1000)
    r:tick(1050)  -- both become NotReady
    r:register({ id = 2 }, 1060)  -- re-register node 2 → Ready
    local ready = r:ready_nodes()
    assert.equals(#ready, 1)
    assert.equals(ready[1].id, 2)
  end)

  it("labels are stored on the record", function()
    local r = Registry.new()
    r:register({ id = 7, labels = { type = "turtle", zone = "overworld" } }, 1000)
    assert.equals(r:get(7).labels.type, "turtle")
    assert.equals(r:get(7).labels.zone, "overworld")
  end)
end)
