local RegistryServer = require("core.registry_server")
local Registry       = require("lib.registry")
local fakes          = require("test.support.fakes")

local function make_server(epoch_ms, transport_override)
  local ctx       = fakes.make_ctx(epoch_ms)
  local transport = transport_override or fakes.make_transport()
  local registry  = Registry.new()
  local server    = RegistryServer.new(ctx, transport, registry, { master_id = 1 })
  return server, transport, registry
end

describe("RegistryServer", function()
  it("REGISTER message registers node and sends ACK", function()
    local server, transport, registry = make_server(5000000)
    transport.inject(7, { type = "REGISTER", id = 7, label = "farm-east" })
    server:step()
    local node = registry:get(7)
    assert.truthy(node)
    assert.equals(node.label, "farm-east")
    assert.equals(node.status, "Ready")
    -- ACK sent back to the registering node
    assert.equals(#transport._sent, 1)
    assert.equals(transport._sent[1].to, 7)
    assert.equals(transport._sent[1].msg.type, "ACK")
    assert.equals(transport._sent[1].msg.master_id, 1)
  end)

  it("HEARTBEAT message updates last_seen", function()
    local server, transport, registry = make_server(5000000)
    registry:register({ id = 7 }, 4000)
    transport.inject(7, { type = "HEARTBEAT", id = 7 })
    server:step()
    assert.equals(registry:get(7).last_seen, 5000)
  end)

  it("unknown message type is silently ignored", function()
    local server, transport, registry = make_server(5000000)
    transport.inject(7, { type = "MAGIC_SPELL", id = 7 })
    local ok = pcall(function() server:step() end)
    assert.truthy(ok)
    assert.is_nil(registry:get(7))
  end)

  it("tick runs even when no message arrives", function()
    local server, _, registry = make_server(5000000)
    -- node registered at t=0 (epoch=0), server steps at t=5000 (epoch=5000000)
    -- with default timeout=45, age=5000 is well past eviction=300 → removed
    -- but let's use a recent timestamp: age = 5 seconds (within timeout)
    registry:register({ id = 7 }, 4995)
    -- no message injected; receive returns nil
    server:step()
    -- node should still be present (age=5 < timeout=45)
    assert.truthy(registry:get(7))
  end)

  it("tick evicts old nodes even with no message", function()
    local server, _, registry = make_server(5000000)
    registry:register({ id = 7 }, 1)
    server:step()
    assert.is_nil(registry:get(7))
  end)

  it("step returns epoch seconds", function()
    local server = make_server(7500000)
    local now = server:step()
    assert.equals(now, 7500)
  end)
end)
